In [1]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [2]:
print(arr.ndim)

1


In [4]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
print(arr2[1,2])

7


In [7]:
print(arr2[1,1:4])

[6 7 8]


In [8]:
print(arr2[0,0:3])

[1 2 3]


In [9]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
print(arr2[0:2,1:3])

[[2 3]
 [7 8]]


In [11]:
print(arr2[0,3])

4


In [12]:
arr2[0,3]=55
print(arr2)

[[ 1  2  3 55  5]
 [ 6  7  8  9 10]]


In [13]:
print(arr2[0:2,1:3])

[[2 3]
 [7 8]]


In [14]:
arr2[0:2,1:3]=[[77,66],[99,88]]
print(arr2)

[[ 1 77 66 55  5]
 [ 6 99 88  9 10]]


In [17]:
ones=np.ones(5,dtype="int")
print(ones)

[1 1 1 1 1]


In [18]:
zeroes=np.zeroes(5,dtype="int")
print(zeroes)

AttributeError: module 'numpy' has no attribute 'zeroes'